INSERT INTO EXCHANGE_CURRENCY(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT_PORT)
VALUES(10001, 'USD', 'INR', 80, '');

INSERT INTO EXCHANGE_CURRENCY(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT_PORT)
VALUES(10002, 'EUR', 'INR', 90, '');

INSERT INTO EXCHANGE_CURRENCY(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT_PORT)
VALUES(10003, 'AUD', 'INR', 25, '');